# Generated by Django 2.1.2 on 2019-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baker',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
