# Generated by Django 2.1.2 on 2019-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baker',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='baker',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
