# Generated by Django 2.1 on 2018-10-10 23:04

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('cooking_time', models.PositiveIntegerField(default=0)),
                ('servings', models.PositiveIntegerField(default=0)),
                ('direction', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('1', 'Easy'), ('2', 'Moderate'), ('3', 'Hard'), ('4', 'Very Hard')], default='1', max_length=1)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
