# Generated by Django 2.1 on 2018-10-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20181011_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='direction',
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(max_length=1800, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
