# Generated by Django 2.1.2 on 2018-10-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20181014_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='image/no_image.png', upload_to='img'),
        ),
    ]
