# Generated by Django 2.1.2 on 2018-10-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20181016_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='no_image.png', upload_to='img'),
        ),
    ]
