# Generated by Django 2.1.2 on 2018-10-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20181020_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='no_image.png', height_field=500, upload_to='', width_field=500),
        ),
    ]
