# Generated by Django 2.1.2 on 2018-10-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20181020_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='no_image.png', upload_to=''),
        ),
    ]
