# Generated by Django 2.1.2 on 2018-10-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20181020_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='directions',
            new_name='instructions',
        ),
    ]
