# Generated by Django 2.1.2 on 2018-10-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20181023_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Moderate'), ('3', 'Hard'), ('4', 'Very Hard')], default='1', max_length=1),
        ),
    ]
