# Generated by Django 2.1.2 on 2019-02-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_baker_slug'),
        ('recipes', '0019_auto_20190211_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='baker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Baker'),
        ),
    ]
